### ISSUE TITLE
feat: Add blogs and youtube videos to each tool and tech

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [kaiwalyakoparkar/practical-devops#10]
I have created videos and blogs for some of the projects and learnings here on https://blogs.kaiwalyakoparkar.com and https://youtube.com/@kaiwalya_koparkar. And others are into production. The task is to add those blogs and videos to respective readme in the folder
eg: You can take look at the readme in Kuberenetes folder

**Comment by akshaya-hub** [comment]
i would like to contribute

**Comment by kaiwalyakoparkar** [comment]
@akshaya-hub go ahead, I will assign it to you :)

**Comment by me-imfhd** [comment]
I would like to help but i don't the idea of what to do

**Comment by kaiwalyakoparkar** [comment]
@me-imfhd sure go ahead, please read the issue descriptions and examples provided and let me know if you face any issue

**Comment by me-imfhd** [comment]
Do you have any work for me related to html and css ...im a beginner and learning web development... I have searched a lot, but never found a single good first issue for me... Can you tell me what should i do

**Comment by kaiwalyakoparkar** [comment]
@me-imfhd you can join https://community.kaiwalyakoparkar.com/ I often share issues there :)

**Comment by me-imfhd** [comment]
Okay i'll wait

**Comment by mnik7044** [comment]
Hey everyone is this issue still open, is anyone working on it if not I would like to work on it.

**Comment by kaiwalyakoparkar** [comment]
@mnik7044 sure you can go ahead with it :)

**Comment by mnik7044** [comment]
Hey @kaiwalyakoparkar I have added your blog and videos of helm and Prometheus and added blog of Argocd as well but you don't have youtube videos and blogs for other topics, can I add youtube videos and blogs from other channels or should I raise a pr ?

**Comment by mnik7044** [comment]
Hey @kaiwalyakoparkar I raised the pr kindly review it.

**Comment by kaiwalyakoparkar** [comment]
With reference to #18
