### ISSUE TITLE
Docker Resuources

### ISSUE THREAD

**Issue by Vedant-MAHAjan** [kaiwalyakoparkar/practical-devops#9]
I went through the repository and found out that Docker learnings, resources, or projects were missing. I recently started learning Docker and would love to contribute to the repo. Please consider the request @kaiwalyakoparkar

**Comment by kaiwalyakoparkar** [comment]
@Vedant-MAHAjan sorry for the late reply but it can be found in https://github.com/kaiwalyakoparkar/practical-devops/tree/main/sample-app and I have also created [blog](https://blogs.kaiwalyakoparkar.com/docker-beginner-to-advance) and [youtube video](https://youtu.be/sBzrInTpJq0) on it. If you want you can check that out too.

**Comment by Vedant-MAHAjan** [comment]
Thanks for the reply. I've checked the resources. I read your blog and found it helpful. I'll definitely check your YouTube video!
